/*
SQLyog v10.2 
MySQL - 5.6.17 : Database - we
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`we` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `we`;

/*Table structure for table `we_plate` */

DROP TABLE IF EXISTS `we_plate`;

CREATE TABLE `we_plate` (
  `ID` int(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `PLATEID` int(5) NOT NULL COMMENT '板块id',
  `TITLE` varchar(100) NOT NULL COMMENT '标题',
  `INFO` varchar(1000) NOT NULL COMMENT '简介',
  `TYPE` varchar(50) NOT NULL COMMENT '类型',
  `URL` varchar(1000) NOT NULL COMMENT '链接',
  `FAPLATEID` int(5) NOT NULL COMMENT '上级板块id',
  `INSERTIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATETIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `STATUS` int(5) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

/*Data for the table `we_plate` */

insert  into `we_plate`(`ID`,`PLATEID`,`TITLE`,`INFO`,`TYPE`,`URL`,`FAPLATEID`,`INSERTIME`,`UPDATETIME`,`STATUS`) values (1,1,'视频','视频','1','',0,'2016-03-25 14:56:46','2016-03-25 14:56:50',0),(2,2,'论坛','论坛','2','',0,'2016-03-25 15:55:45','2016-03-25 15:55:45',0);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
