package com.we.code.model;

// default package
// Generated 2016-3-28 9:03:17 by Hibernate Tools 4.0.0.Final

import java.util.Date;

import org.hibernate.annotations.Entity;

/**
 * WePlate generated by hbm2java
 */
@Entity
public class WePlate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7268643944495352261L;
	private Integer id;
	private Integer plateid;
	private String title;
	private String info;
	private String type;
	private String url;
	private int faplateid;
	private Date insertime;
	private Date updatetime;
	private int status;

	public WePlate() {
	}

	public WePlate(Integer plateid, String title, String info, String type, String url, int faplateid, Date insertime,
			Date updatetime, int status) {
		this.plateid = plateid;
		this.title = title;
		this.info = info;
		this.type = type;
		this.url = url;
		this.faplateid = faplateid;
		this.insertime = insertime;
		this.updatetime = updatetime;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPlateid() {
		return this.plateid;
	}

	public void setPlateid(Integer plateid) {
		this.plateid = plateid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public int getFaplateid() {
		return this.faplateid;
	}

	public void setFaplateid(int faplateid) {
		this.faplateid = faplateid;
	}

	public Date getInsertime() {
		return this.insertime;
	}

	public void setInsertime(Date insertime) {
		this.insertime = insertime;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}
}
