package com.we.code.model;

// default package
// Generated 2016-3-28 9:03:17 by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * WePost generated by hbm2java
 */
public class WePost implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5254967511014126045L;
	private Integer id;
	private String title;
	private String summary;
	private String type;
	private int reading;
	private int praise;
	private int collection;
	private int status;
	private String link;
	private Integer userid;
	private Date createtime;
	private Integer plateid;

	public WePost() {
	}

	public WePost(String title, String type, int reading, int praise, int collection, int status, Date createtime) {
		this.title = title;
		this.type = type;
		this.reading = reading;
		this.praise = praise;
		this.collection = collection;
		this.status = status;
		this.createtime = createtime;
	}

	public WePost(String title, String summary, String type, int reading, int praise, int collection, int status,
			String link, Integer userid, Date createtime, Integer plateid) {
		this.title = title;
		this.summary = summary;
		this.type = type;
		this.reading = reading;
		this.praise = praise;
		this.collection = collection;
		this.status = status;
		this.link = link;
		this.userid = userid;
		this.createtime = createtime;
		this.plateid = plateid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getReading() {
		return this.reading;
	}

	public void setReading(int reading) {
		this.reading = reading;
	}

	public int getPraise() {
		return this.praise;
	}

	public void setPraise(int praise) {
		this.praise = praise;
	}

	public int getCollection() {
		return this.collection;
	}

	public void setCollection(int collection) {
		this.collection = collection;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Integer getPlateid() {
		return this.plateid;
	}

	public void setPlateid(Integer plateid) {
		this.plateid = plateid;
	}

}
